/**
 * Minified Coolbet Bookmarklet - PRODUCTION READY
 * 
 * VERIFIED SELECTORS - Based on actual Coolbet DOM (December 2025)
 * 
 * Copy the entire javascript: URL below and create a bookmark with it.
 */

// PRODUCTION VERSION (using Render backend)
export const COOLBET_BOOKMARKLET_PROD = `javascript:(async function(){'use strict';const API='https://bet-tracker-backend-rqjp.onrender.com/api/bets/import/coolbet';try{if(!window.confirm('Import Coolbet bets into Bet Tracker?'))return;const rows=document.querySelectorAll('.bet-ticket');if(rows.length===0){alert('No bets found on this page.\\n\\nPlease ensure:\\n1. You are on the bet history page\\n2. Bet history has loaded');return}const bets=Array.from(rows).map((row)=>{const ticketId=row.querySelector('.ticket-id')?.innerText.replace('#','').trim();const sport=row.querySelector('svg[data-name]')?.getAttribute('data-name')??'unknown';const league=row.querySelector('.match-league')?.innerText.trim();const event=row.querySelector('.match-name')?.innerText.trim();const market=row.querySelector('.market-name')?.innerText.trim();const outcome=row.querySelector('.market-outcome')?.innerText.trim();const oddsText=row.querySelector('.ticket-total-odds')?.innerText;const odds=parseFloat(oddsText?.replace(',','.')||'1.0');const stakeText=row.querySelector('.ticket-total-stake')?.innerText;const stake=parseFloat(stakeText?.replace(/[^\\d,]/g,'').replace(',','.')||'0');const statusText=row.querySelector('.bet-status')?.innerText.toLowerCase();const result=statusText?.includes('won')?'won':statusText?.includes('lost')?'lost':'pending';const betDescription=market&&outcome?\`\${market} - \${outcome}\`:(market||outcome||event);return{externalId:\`coolbet-\${ticketId}\`,event:event||'Unknown Event',stake:stake,odds:odds,result:result,placedAt:new Date().toISOString(),selection:betDescription,betType:'single',sport:sport,league:league,market:market,outcome:outcome}});const validBets=bets.filter(bet=>bet.externalId&&bet.stake>0&&bet.odds>0);if(validBets.length===0){alert('No valid bets found to import.');return}console.log(\`Found \${validBets.length} valid bets to import:\`,validBets);const response=await fetch(API,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({source:'coolbet',bets:validBets})});if(!response.ok){const errorText=await response.text();alert(\`Import failed: \${response.status} \${response.statusText}\\n\\nCheck console for details.\`);console.error('Import error:',errorText);return}const result=await response.json();alert(\`✅ Import Complete!\\n\\nTotal: \${result.total}\\nImported: \${result.imported}\\nSkipped (duplicates): \${result.skipped}\`)}catch(error){alert(\`❌ Import Failed\\n\\nError: \${error.message}\\n\\nPlease ensure:\\n1. You are logged into your Bet Tracker app\\n2. You are on the Coolbet bet history page\\n3. Your internet connection is working\`);console.error('Bookmarklet error:',error)}})();`;

// DEVELOPMENT VERSION (for localhost testing)
export const COOLBET_BOOKMARKLET_DEV = `javascript:(async function(){'use strict';const API='http://localhost:8000/api/bets/import/coolbet';try{if(!window.confirm('Import Coolbet bets into Bet Tracker?'))return;const rows=document.querySelectorAll('.bet-ticket');if(rows.length===0){alert('No bets found on this page.\\n\\nPlease ensure:\\n1. You are on the bet history page\\n2. Bet history has loaded');return}const bets=Array.from(rows).map((row)=>{const ticketId=row.querySelector('.ticket-id')?.innerText.replace('#','').trim();const sport=row.querySelector('svg[data-name]')?.getAttribute('data-name')??'unknown';const league=row.querySelector('.match-league')?.innerText.trim();const event=row.querySelector('.match-name')?.innerText.trim();const market=row.querySelector('.market-name')?.innerText.trim();const outcome=row.querySelector('.market-outcome')?.innerText.trim();const oddsText=row.querySelector('.ticket-total-odds')?.innerText;const odds=parseFloat(oddsText?.replace(',','.')||'1.0');const stakeText=row.querySelector('.ticket-total-stake')?.innerText;const stake=parseFloat(stakeText?.replace(/[^\\d,]/g,'').replace(',','.')||'0');const statusText=row.querySelector('.bet-status')?.innerText.toLowerCase();const result=statusText?.includes('won')?'won':statusText?.includes('lost')?'lost':'pending';const betDescription=market&&outcome?\`\${market} - \${outcome}\`:(market||outcome||event);return{externalId:\`coolbet-\${ticketId}\`,event:event||'Unknown Event',stake:stake,odds:odds,result:result,placedAt:new Date().toISOString(),selection:betDescription,betType:'single',sport:sport,league:league,market:market,outcome:outcome}});const validBets=bets.filter(bet=>bet.externalId&&bet.stake>0&&bet.odds>0);if(validBets.length===0){alert('No valid bets found to import.');return}console.log(\`Found \${validBets.length} valid bets to import:\`,validBets);const response=await fetch(API,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({source:'coolbet',bets:validBets})});if(!response.ok){const errorText=await response.text();alert(\`Import failed: \${response.status} \${response.statusText}\\n\\nCheck console for details.\`);console.error('Import error:',errorText);return}const result=await response.json();alert(\`✅ Import Complete!\\n\\nTotal: \${result.total}\\nImported: \${result.imported}\\nSkipped (duplicates): \${result.skipped}\`)}catch(error){alert(\`❌ Import Failed\\n\\nError: \${error.message}\\n\\nPlease ensure:\\n1. You are logged into your Bet Tracker app\\n2. You are on the Coolbet bet history page\\n3. Your internet connection is working\`);console.error('Bookmarklet error:',error)}})();`;

console.log('=== COOLBET IMPORT BOOKMARKLET - READY TO USE ===\n');
console.log('PRODUCTION (Render backend):\n');
console.log(COOLBET_BOOKMARKLET_PROD);
console.log('\n\nDEVELOPMENT (localhost):\n');
console.log(COOLBET_BOOKMARKLET_DEV);
